### ISSUE TITLE
Bug with Overview Pie Chart

### ISSUE THREAD

**Issue by ghost** [x-tools/SuperCount#29]
If you wiggle your mouse on and off of the big pie chart repetitively it just grows bigger and bigger. 

Ok can't tell if the image worked (my preview button isn't working) so here is a link http://i.imgur.com/Cu7Kh0P.png

**Comment by ghost** [comment]
<a href="http://imgur.com/Cu7Kh0P"><img src="http://i.imgur.com/Cu7Kh0P.png" title="source: imgur.com" /></a>

**Comment by cyberpower678** [comment]
Not in my control.

**Comment by ricordisamoa** [comment]
@EoRdE6: it is an old bug presumably due to some code I copied from [gRaphaël's Interactive Pie Chart example](http://g.raphaeljs.com/piechart2.html) and by which SuperCount may have been inspired.

@cyberpower678: it should be easy to fix, just apply https://github.com/DmitryBaranovskiy/g.raphael/pull/209 (it is for the demo, but applies to your chart as well).

Incidentally, I fixed it [by using D3.js instead](//github.com/ricordisamoa/dewkin/commit/47a38bbdb0bca021429570ab70d1fbfefafa5180).
